name: SonarQube Pipeline

on:
  push:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 🔍 SonarQube Scan (CONFIG PASSED HERE)
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=hospital-management-system
            -Dsonar.projectName="Hospital Management System"
            -Dsonar.sources=.
            -Dsonar.language=java
            -Dsonar.sourceEncoding=UTF-8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # 🚨 Quality Gate Check
      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # ❌ Send failure mail
      - name: Send Failure Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Build Failed - Vulnerabilities Found"
          body: "Pipeline failed due to vulnerabilities. Check SonarQube."
          to: ${{ secrets.DEVOPS_EMAIL }}
          from: DevOps Alert

      # ✅ Send success mail
      - name: Send Success Email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Build Success - No Vulnerabilities"
          body: "Pipeline passed successfully."
          to: ${{ secrets.DEVOPS_EMAIL }}
          from: DevOps Alert